DROP TABLE IF EXISTS RESERVATIONS;
DROP TABLE IF EXISTS RESERVATIONS CASCADE;
DROP TABLE IF EXISTS RESOURCES CASCADE;
DROP TABLE IF EXISTS DEPARTMENT CASCADE;
DROP TABLE IF EXISTS USERS CASCADE;

CREATE TABLE USERS (
    user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(20) NOT NULL,
    last_name VARCHAR(20) NOT NULL,
    email VARCHAR(50) NOT NULL UNIQUE,
    phone_number VARCHAR(15),
    user_role VARCHAR(20) NOT NULL CHECK (user_role IN ('manager', 'admin', 'user')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, 
    status VARCHAR(20) NOT NULL CHECK (status IN ('active', 'inactive'))
);


CREATE TABLE DEPARTMENT (
    department_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    location VARCHAR(100) NOT NULL,
    manager_id INT,
    description VARCHAR(100)
);


CREATE TABLE RESOURCES (
    resource_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_id INT NOT NULL REFERENCES DEPARTMENT(department_id),
    name VARCHAR(50) NOT NULL, 
    resource_type VARCHAR(30) NOT NULL CHECK (resource_type IN ('room', 'car', 'equipment')),
    description VARCHAR(100),
    location VARCHAR(100) NOT NULL,
    status VARCHAR(30) NOT NULL CHECK (status IN ('available', 'maintenance', 'inactive')), 
    capacity INT NULL
);


CREATE TABLE RESERVATIONS (
    reservation_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL REFERENCES USERS(user_id),
    resource_id INT NOT NULL REFERENCES RESOURCES(resource_id),
    start_time TIMESTAMP NOT NULL, 
    end_time TIMESTAMP NOT NULL, 
    status VARCHAR(30) NOT NULL CHECK (status IN ('pending', 'confirmed', 'cancelled')),
    purpose VARCHAR(50) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT check_reservation_dates CHECK (start_time < end_time)
);

-- strani kljuc kako bih zaobisla kruznu ovisnost
ALTER TABLE DEPARTMENT 
ADD CONSTRAINT fk_department_manager 
FOREIGN KEY (manager_id) REFERENCES USERS(user_id) ON DELETE SET NULL;