
CREATE TABLE IF NOT EXISTS reservations_audit (
    audit_id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_id  INT NOT NULL,
    old_status      VARCHAR(50),
    new_status      VARCHAR(50),
    changed_by      VARCHAR(100),
    changed_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- prvo kreiram trigger funkciju
CREATE OR REPLACE FUNCTION fnc_trg_reservations_audit()
RETURNS TRIGGER 
LANGUAGE plpgsql AS $$
DECLARE
    v_user VARCHAR(100);
BEGIN
    
    v_user := current_user;

    IF OLD.status IS DISTINCT FROM NEW.status THEN
        INSERT INTO reservations_audit (
            reservation_id, 
            old_status, 
            new_status, 
            changed_by, 
            changed_at
        ) VALUES (
            OLD.reservation_id,
            OLD.status,
            NEW.status,
            v_user,
            CURRENT_TIMESTAMP   
        );
    END IF;
 
    RETURN NEW;
END;
$$;


DROP TRIGGER IF EXISTS trg_reservations_audit ON RESERVATIONS;

CREATE TRIGGER trg_reservations_audit
AFTER UPDATE OF status ON RESERVATIONS
FOR EACH ROW
EXECUTE FUNCTION fnc_trg_reservations_audit();